apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-events-reader
  namespace: demo
subjects:
- kind: ServiceAccount
  name: demo
  namespace: demo
roleRef:
  kind: Role
  name: events-reader
  apiGroup: rbac.authorization.k8s.io
